sudo: required
services:
  - docker

before_install:
  - docker build -t fish417913/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fish417913/react-test npm test

after_success:
  - docker build -t fish417913/multi-client ./client
  - docker build -t fish417913/multi-nginx ./nginx
  - docker build -t fish417913/multi-server ./server
  - docker build -t fish417913/multi-worker ./worker
  